const survivorNames = [
  "Steady Aim",
  "Rapid Reload",
  "Light Armor",
  "Vitality Training I",
  "Sprint Training",
  "Ammo Pouch",
  "Bandage",
  "Fragmentation Grenade",
  "Weak Point Analysis",
  "Recoil Control",
  "Sharpened Blades",
  "Survival Instinct",
  "Fireproof Fabric",
  "Sandstep",
  "Infernal Talisman",
  "Indoor Recon",
  "Knockback Training",
  "Lucky Pockets",
  "First Aid Training",
  "Grenade Pouch",
  "Listening Replay Ticket",
  "Extra Thinking Time",
  "Rescue Focus",
  "Boss Hunter I",
  "Vitality Training II",
  "Reinforced Armor Plates",
  "High-Speed Action",
  "Extended Magazine II",
  "Precision Barrel",
  "Minor Life Drain",
  "Twin Grenade",
  "Medkit",
  "Adrenaline",
  "Penetrating Rounds",
  "Sword Mastery",
  "Spear Sweep",
  "Sniper Breath Control",
  "SMG Overdrive",
  "Assault Tactics",
  "Cryo Ammunition",
  "Incendiary Ammunition",
  "Rescue Buffer",
  "Fate Reroll",
  "Boss Hunter II",
  "Laser Rifle",
  "Elemental Staff",
  "Prototype Lightblade",
  "Grenade Launcher",
  "Tesla Grenade",
  "Auto Turret",
  "Shield Generator",
  "Emergency Revival Kit",
  "Elemental Convergence",
  "Bursting Rounds",
  "Chain Lightning",
  "Combat Drone",
  "Temporal Reload",
  "Critical Chain",
  "Phoenix Bandage",
  "Boss Armor Break",
  "Perfected Lightblade",
  "Archmage Scepter",
  "Plasma Cannon",
  "Singularity Grenade",
  "Orbital Laser Beacon",
  "Aegis Field",
  "Replicating Turret",
  "Time Dilation",
  "Infinite Sword Dance",
  "Phoenix Protocol",
  "Life Link",
  "Doomsday Magazine",
  "Black Hole Staff",
  "Solar Lightblade",
  "Omega Laser",
  "Sacred Arsenal",
  "World Stasis",
  "Undying Core",
  "Boss Devourer",
  "Final Protocol",
  "Lightweight Stock",
  "Scavenger Boots",
  "Quick Hands",
  "Field Rations",
  "Shoulder Brace",
  "Insulated Lining",
  "Toxin Filter",
  "Thermal Weave",
  "Sure Footing",
  "Reserve Chamber",
  "Close Quarters Combat",
  "Long-Range Calibration",
  "Tactical Sidestep",
  "Stable Guard",
  "Healing Spray",
  "Ammo Sharing",
  "Squad Locator",
  "Objective Specialist",
  "Rescue Bracer",
  "Turret Maintenance",
  "Drone Battery",
  "Elemental Primer",
  "Execution Training",
  "Adaptive Optic",
  "Double-Tap Trigger",
  "Suppressive Fire",
  "Counter Stance",
  "Spear Charge",
  "Energy-Draining Blade",
  "Ricochet",
  "Demolitions Expert",
  "Combat Medic",
  "Armored Rescue",
  "Tactical Supply Crate",
  "Pulse Mine",
  "Cryo Trap",
  "Incendiary Trap",
  "Guardian Drone",
  "Shield Overcharge",
  "Skill Accelerator",
  "Commander Hunter",
  "Combo Safeguard",
  "Second Choice",
  "Elite Hunter",
  "Orbital Rail Rifle",
  "Phase SMG",
  "Storm Assault Rifle",
  "Void Spear",
  "Crimson Moon Sword",
  "Nano Medkit",
  "Gravity Mine",
  "Flame Turret",
  "Frost Turret",
  "Medical Drone",
  "Mirror Shield",
  "Arc Capacitor",
  "Soul Battery",
  "Shared Arsenal",
  "Emergency Teleport",
  "Adaptive Evolution",
  "Celestial Rail Cannon",
  "Phantom Repeater",
  "Stormlord Rifle",
  "Void Impaler",
  "Eclipse Blade",
  "Nanite Swarm",
  "Fortress Network",
  "Guardian Angel Drone",
  "Quantum Duplication",
  "Elemental Sovereign",
  "Last Stand Covenant",
  "Temporal Reserve",
  "Starfall Railgun",
  "Phantom Swarm",
  "Thunder God's Decree",
  "Abyssal Godlance",
  "Eclipse Judgment",
  "Immortal Legion",
  "Causal Rewrite",
  "Dawn Protocol",
] as const;

const zombieNames = [
  "Crystal Husk Proliferation",
  "Razor Claws",
  "Impulse Lattice",
  "Hardened Shell",
  "Frenzied Conduits",
  "Hunter Sense",
  "Acid Gland Amplification",
  "Charge Lattice",
  "Swarm Instinct",
  "Boss Crystal Density",
  "Infection Recirculation",
  "Dormant Regeneration",
  "Corrosive Wound",
  "Chilling Touch",
  "Searing Crystal Residue",
  "Spore Shield",
  "Shared Vision",
  "Elite Incubation",
  "Reanimation Impulse",
  "Boss Fury",
  "Infection Interest",
  "Hunter's Mark",
  "Screamer Resonance",
  "Crystal Horde Formation",
  "Carapace Commander",
  "Relentless Acceleration",
  "Psychic Rend",
  "Terrain Corruption",
  "Collective Life Drain",
  "Boss Armor Rupture",
  "Temporal Blight Zone",
  "Psychic Terror",
  "Elemental Adaptation",
  "Symbiotic Vitality",
  "Pursuit Leap",
  "Boss Phase Shift",
  "Eternal Night Corruption",
  "Hive Will",
  "Calamity Avatar",
  "Doomsday Infection",
  "Crystal Crown",
  "Crystal Spike Carapace",
  "Shattered Husk Burst",
  "Crystal Dust",
  "Unrelenting Stride",
  "Echo Hearing",
  "Acidic Crystal Spray",
  "Crystal Armor",
  "Group Guard",
  "Ambush",
  "Burrowing Claws",
  "Expanded Resonance Sac",
  "Volatile Core",
  "Frost Core",
  "Ember Core",
  "Boss Hunger",
  "Infection Reserves",
  "Spawn Camouflage",
  "Siege Lattice",
  "Plague Spit",
  "Hunter Leap",
  "Bulwark Proliferation",
  "Decay Link",
  "Relay Instinct",
  "Rallying Howl",
  "Mutation Reserve",
  "Trap Instinct",
  "Crystal Anchor",
  "Vengeful Spores",
  "Commander Efficiency",
  "Player Crystal Husk",
  "Boss Talisman",
  "Final Crystal Horde",
  "Colossus Genome",
  "Phantom Plague",
  "Crystal Cage",
  "Crimson Crystal Mist",
  "Corrosive Rain",
  "Incubation Nest",
  "Elite Command Chain",
  "Predatory Evolution",
  "Infection Tax",
  "Psychic Mirror",
  "Boss Soul Fracture",
  "Death March",
  "Time Eater",
  "Spatial Rift",
  "Rotating Immunity",
  "Cataclysm Spores",
  "Hive Revival",
  "Abyssal Carapace",
  "Commander Avatar",
  "Twin Bosses",
  "Irreversible Infection",
  "Red Moon Finale",
  "Undying Hive",
  "World Plague",
  "Endless Hunt",
  "Extinction Form",
  "Final Cataclysm",
] as const;

const toStableNameMap = (
  prefix: "S" | "Z",
  names: readonly string[],
): Readonly<Record<string, string>> =>
  Object.freeze(
    Object.fromEntries(
      names.map((name, index) => [
        `${prefix}${String(index + 1).padStart(3, "0")}`,
        name,
      ]),
    ),
  );

export const CARD_ENGLISH_NAMES = Object.freeze({
  ...toStableNameMap("S", survivorNames),
  ...toStableNameMap("Z", zombieNames),
});
